class Solution {
public:
    int smallestNumber(int n) {
        // All numbers consisting of only 1's are generated by the equation (i*2)+1
        int i = 1;
        while (n >= i) {
            if (i == n) {
                return i;
            }
            i = (i * 2) + 1;
        }
        return i;
    }
};
